services:
  app:
    build: ./
    container_name: lecture-backend
    volumes:
      - .:/app:rw
    ports:
      - 127.0.0.1:10990:80/tcp
    depends_on:
      - database

  database:
    image: mongo:5.0
    container_name: lecture-backend-database
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
